version: "3.3"
services:
  mongodb:
    image: mongo:3.7
    container_name: mongodb

    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secr3t

    ports:
      - "27017:27017"

    volumes:
      - f:\docker-volumes\mongodb\db:/data/db
